version: '2'
services:
    test-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/test/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
